[versions]
androidGradlePlugin = "8.13.2"
kotlinGradlePlugin = "2.3.0"
mavenPublish = "0.35.0"

activityCompose = "1.12.2"
coreKtx = "1.17.0"
lifecycleRuntimeKtx = "2.10.0"
androidxComposeBom = "2025.12.01"
retrofit = "3.0.0"
espressoCore = "3.7.0"
junit = "4.13.2"
junitVersion = "1.3.0"
appcompat = "1.7.1"
material = "1.13.0"

startupAndroid = "1.2.0"
koin = "4.1.1"
uiautomator = "2.3.0"
benchmarkMacroJunit4 = "1.4.1"
baselineprofile = "1.4.1"
profileinstaller = "1.4.1"

[libraries]
#Compose
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }

androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }

retrofit_core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit_gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }

koin-bom = { group = "io.insert-koin", name = "koin-bom", version.ref = "koin" }
koin-core = { group = "io.insert-koin", name = "koin-core" }
koin-android = { group = "io.insert-koin", name = "koin-android" }
koin-coroutine = { group = "io.insert-koin", name = "koin-core-coroutines" }
koin-androidx-startup = { group = "io.insert-koin", name = "koin-androidx-startup" }

startup-android = { module = "androidx.startup:startup-runtime", version.ref = "startupAndroid" }

koin-startup-extension-local = { module = "com.santimattius.android:koin-startup-extension", version = "2.0.0-alpha01" }
koin-startup-extension-remote = { module = "com.github.santimattius:android-koin-startup-extension", version = "2.0.0-alpha02" }

#Testing
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
junit = { module = "junit:junit", version.ref = "junit" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
androidx-benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmarkMacroJunit4" }
androidx-profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "profileinstaller" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinGradlePlugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinGradlePlugin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
baselineprofile = { id = "androidx.baselineprofile", version.ref = "baselineprofile" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }